function updateVal(q,h_q,T,h_T)

    s1 = strcat('Current Configuration:',mat2str(q,3));
    set(h_q,'String',s1);
    
    s2 = strvcat('Current EE Orientation:',...
                mat2str(T(1,1:3),3),...
                mat2str(T(2,1:3),3),...
                mat2str(T(3,1:3),3),...
                ' ',...
                'Current EE Position:',...
                mat2str(T(1:3,4),3));
            
    set(h_T,'String',s2);

end